import 'package:flutter/widgets.dart';
import 'package:lucide_icons/lucide_icons.dart';

/// Category, group, and goal icons are stored as a Lucide icon name string
/// (e.g. `"utensils-crossed"`) — see `frontend/src/lib/category-icons.ts`,
/// the picker every icon in this app can come from. This is that same list,
/// so a category picked on the web looks identical on the phone rather than
/// falling back to a generic dot.
const Map<String, IconData> _lucideIconMap = {
  'house': LucideIcons.home,
  'lightbulb': LucideIcons.lightbulb,
  'droplets': LucideIcons.droplets,
  'flame': LucideIcons.flame,
  'wifi': LucideIcons.wifi,
  'tv': LucideIcons.tv,
  'utensils-crossed': LucideIcons.utensilsCrossed,
  'coffee': LucideIcons.coffee,
  'beer': LucideIcons.beer,
  'pizza': LucideIcons.pizza,
  'salad': LucideIcons.salad,
  'car': LucideIcons.car,
  'fuel': LucideIcons.fuel,
  'bus': LucideIcons.bus,
  'train': LucideIcons.train,
  'plane': LucideIcons.plane,
  'bike': LucideIcons.bike,
  'shopping-cart': LucideIcons.shoppingCart,
  'shopping-bag': LucideIcons.shoppingBag,
  'gift': LucideIcons.gift,
  'shirt': LucideIcons.shirt,
  'pill': LucideIcons.pill,
  'stethoscope': LucideIcons.stethoscope,
  'syringe': LucideIcons.syringe,
  'cross': LucideIcons.cross,
  'heart': LucideIcons.heart,
  'dumbbell': LucideIcons.dumbbell,
  'gamepad-2': LucideIcons.gamepad2,
  'music': LucideIcons.music,
  'film': LucideIcons.film,
  'party-popper': LucideIcons.partyPopper,
  'smartphone': LucideIcons.smartphone,
  'credit-card': LucideIcons.creditCard,
  'book-open': LucideIcons.bookOpen,
  'graduation-cap': LucideIcons.graduationCap,
  'briefcase': LucideIcons.briefcase,
  'building-2': LucideIcons.building2,
  'landmark': LucideIcons.landmark,
  'wallet': LucideIcons.wallet,
  'banknote': LucideIcons.banknote,
  'piggy-bank': LucideIcons.piggyBank,
  'trending-up': LucideIcons.trendingUp,
  'trending-down': LucideIcons.trendingDown,
  'receipt': LucideIcons.receipt,
  'arrow-left-right': LucideIcons.arrowLeftRight,
  'baby': LucideIcons.baby,
  'dog': LucideIcons.dog,
  'cat': LucideIcons.cat,
  'scissors': LucideIcons.scissors,
  'wrench': LucideIcons.wrench,
  'hammer': LucideIcons.hammer,
  'tree-pine': LucideIcons.treePine,
  'umbrella': LucideIcons.umbrella,
  'globe': LucideIcons.globe,
  'sparkles': LucideIcons.sparkles,
  'circle-help': LucideIcons.helpCircle,
  // Category-group, split-group, and other non-category icon defaults.
  'folder': LucideIcons.folder,
  'users': LucideIcons.users,
  'flag': LucideIcons.flag,
  'target': LucideIcons.target,
  'handshake': LucideIcons.heartHandshake,
  'repeat': LucideIcons.repeat,
  'tag': LucideIcons.tag,
  'tune': LucideIcons.slidersHorizontal,
};

/// Resolves a stored icon name to the Lucide glyph the web app shows for it,
/// falling back to a neutral question mark for a name added to the web app's
/// picker after this map was last updated.
IconData lucideIcon(String? name) =>
    _lucideIconMap[name] ?? LucideIcons.helpCircle;
